services:
    mysql-db:
        image: mysql:8.4.3
        container_name: ironmongers-database
        restart: always
        ports:
            - "3306:3306"
        env_file:
          - .env
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        volumes:
            - ./mysql:/var/lib/mysql

volumes:
    mysql:
        driver: local
